name: MCRpy 
channels: 
  - defaults 
  - pytorch
  - conda-forge
dependencies: 
  - python=3.8
  - numpy=1.20.1  
  - matplotlib=3.3.4 
  - scipy=1.6.2 
  - pyMKS=0.4.1 
  - scikit-learn=0.24.1 
  - imageio-ffmpeg=0.4.5 
  - Gooey=1.0.8.1 
  - pyevtk=1.4.1 
  - pip
  - pip:
    - tensorflow==2.7.1
