name: FastGAN
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pandas==1.5.3
  - numpy==1.23.5
  - tqdm==4.64.1
  - scipy==1.10.1
  - scikit-image==0.20.0
  - ipdb==0.13.3
  - lmdb
  - easing-functions==1.0.4
  - torchvision==0.15.1
  - pip
  - pip:
    - torch==2.0.0+cu118 
    - torchvision==0.15.1+cu118 
    - opencv-python-headless==4.5.4.60
